name: Docker Build & Push

on:
  push:
    paths-ignore:
      - "**.md"
      - "/**.gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  logrotate:
    uses: thesilkky/workflows/.github/workflows/docker-build-push.yml@main
    with:
      image: thesilkky/logrotate
      context: .
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
